<?php
/**
 * CyberNanny AI Advisor — usage tiers (sanitized showcase).
 *
 * The advisor is available on every plan; limits differ. A pre-AI screener
 * answers dead-end questions ("track a phone by number without an app" is
 * a scam, we say so) from canned responses without spending tokens or the
 * user's daily quota.
 */

const TIERS = [
    'free'    => ['chat_per_day' => 1,  'weekly_summary' => false],
    'pro'     => ['chat_per_day' => 10, 'weekly_summary' => true],
];

function advisorAllowance(User $parent): array
{
    return TIERS[$parent->tier()] ?? TIERS['free'];
}

/**
 * Weekly summaries are generated by a stronger model and cached per device
 * for seven days; the chat runs on a lightweight model. Two-tier model
 * selection plus prompt caching keeps the cost of an AI conversation low
 * enough to include it in a freemium product.
 */
